import play.sbt.routes.RoutesKeys
import sbt.Def
import scoverage.ScoverageKeys
import uk.gov.hmrc.DefaultBuildSettings
import uk.gov.hmrc.versioning.SbtGitVersioning.autoImport.majorVersion

lazy val appName: String = "register-country-by-country-reporting-frontend"
ThisBuild / majorVersion := 0
ThisBuild / scalaVersion := "3.3.6"

lazy val root = (project in file("."))
  .enablePlugins(PlayScala, SbtDistributablesPlugin)
  .disablePlugins(JUnitXmlReportPlugin) //Required to prevent https://github.com/scalatest/scalatest/issues/1427
  .settings(inConfig(Test)(testSettings): _*)
  .settings(ThisBuild / useSuperShell := false)
  .settings(
    ThisBuild / scalafmtOnCompile := true,
    name                          := appName,
    RoutesKeys.routesImport ++= Seq(
      "models._",
      "uk.gov.hmrc.play.bootstrap.binders.RedirectUrl"
    ),
    TwirlKeys.templateImports ++= Seq(
      "play.twirl.api.HtmlFormat",
      "play.twirl.api.HtmlFormat._",
      "uk.gov.hmrc.govukfrontend.views.html.components._",
      "uk.gov.hmrc.hmrcfrontend.views.html.components._",
      "uk.gov.hmrc.hmrcfrontend.views.html.helpers._",
      "views.ViewUtils._",
      "models.Mode",
      "controllers.routes._",
      "viewmodels.govuk.all._"
    ),
    PlayKeys.playDefaultPort := 10026,
    ScoverageKeys.coverageExcludedFiles := Seq(
      "<empty>",
      ".*Reverse.*",
      ".*Routes.*",
      ".*standardError*.*",
      ".*main_template*.*",
      "uk.gov.hmrc.BuildInfo",
      "app.*",
      "prod.*",
      "config.*",
      "testOnlyDoNotUseInAppConf.*",
      "views.html.*",
      "testOnly.*",
      ".*/models/.*",
      ".*/utils/.*",
      ".*.metrics.*",
      ".*.audit.*",
      ".*javascript.*",
      ".*GuiceInjector;",
      ".*ControllerConfiguration",
      ".*LanguageSwitchController",
      ".*handlers.*",
      ".*Repository.*",
      ".*repositories.*",
      ".*components.*",
      ".*viewmodels.govuk.*"
    ).mkString(";"),
    ScoverageKeys.coverageMinimumStmtTotal := 85,
    ScoverageKeys.coverageFailOnMinimum    := true,
    ScoverageKeys.coverageHighlighting     := true,
    scalacOptions ++= Seq("-feature"),
    libraryDependencies ++= AppDependencies(),
    retrieveManaged := true,
    // concatenate js
    Concat.groups := Seq(
      "javascripts/application.js" ->
        group(
          Seq(
            "javascripts/app.js"
          )
        )
    ),
    uglifyOps := UglifyOps.singleFile,
    // prevent removal of unused code which generates warning errors due to use of third-party libs
    uglifyCompressOptions := Seq("unused=false", "dead_code=false"),
    pipelineStages        := Seq(digest),
    // below line required to force asset pipeline to operate in dev rather than only prod
    Assets / pipelineStages := Seq(concat, uglify),
    // only compress files generated by concat
    uglify / includeFilter := GlobFilter("application.js")
  )
  .settings(
    scalacOptions ++= Seq(
      "-release", "11",
      "-Wconf:src=views/.*:s",
      "-Wconf:src=routes/.*:s",
      "-Wconf:src=.*/Routes.scala:s",
      "-Wconf:src=.*/RoutesPrefix.scala:s",
      "-Wconf:src=.*/ReverseRoutes.scala:s",
      "-Wconf:src=.*/test/.*:s",
      "-Wconf:cat=deprecation:s"
    ),
    scalacOptions := scalacOptions.value.distinct
  )

lazy val testSettings: Seq[Def.Setting[_]] = Seq(
  fork := true,
  javaOptions ++= Seq(
    "-Dconfig.resource=test.application.conf"
  ),
  Test / unmanagedSourceDirectories += baseDirectory.value / "test-utils"
)

lazy val it = project
  .enablePlugins(PlayScala)
  .dependsOn(root % "test->test")
  .settings(DefaultBuildSettings.itSettings(), scalacOptions := scalacOptions.value.distinct)
  .settings(libraryDependencies ++= AppDependencies.itDependencies)
